ACCOUNT_TYPE_NAMES = {
    "ACCOUNT_TYPE_C2C_YBB": "C2C YBB",
    "ACCOUNT_TYPE_FIXED_RATE_LOAN": "Fixed Rate Loan",
    "ACCOUNT_TYPE_LAUNCHPOOL": "LaunchPool",
    "ACCOUNT_TYPE_PLEDGE_LOANS": "Pledge Loans",
    "ACCOUNT_TYPE_PRE_MARKET_TRADING": "Pre-market Trading",
    "ACCOUNT_TYPE_UNIFIED": "Unified",
    "ACCOUNT_TYPE_FUND": "Fund",
    "ACCOUNT_TYPE_INVESTMENT": "Investment",
    "ACCOUNT_TYPE_COPY_TRADE_ALL": "Copy Trade (All)",
    "ACCOUNT_TYPE_COPY_TRADE": "Copy Trade",
    "ACCOUNT_TYPE_COPY_PRO": "Copy Pro",
    "ACCOUNT_TYPE_BOT": "Bot"
}
